const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
const EMPTY_CART = 'EMPTY_CART';
const TRANSFER_DATA_TO_CART_FROM_DB = 'TRANSFER_DATA_TO_CART_FROM_DB';

export {
  ADD_PRODUCT_TO_CART,
  REMOVE_PRODUCT_FROM_CART,
  EMPTY_CART,
  TRANSFER_DATA_TO_CART_FROM_DB,
}
