const EMPTY_CART = 'EMPTY_CART';
const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
const TRANSFER_DATA_TO_CART_FROM_DB = 'TRANSFER_DATA_TO_CART_FROM_DB';
const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';

export {
  EMPTY_CART,
  ADD_PRODUCT_TO_CART,
  TRANSFER_DATA_TO_CART_FROM_DB,
  REMOVE_PRODUCT_FROM_CART,
}
