const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
const OPEN_CART = 'OPEN_CART';
const CLOSE_CART = 'CLOSE_CART';

export {
  ADD_PRODUCT_TO_CART,
  REMOVE_PRODUCT_FROM_CART,
  OPEN_CART,
  CLOSE_CART,
}
