const SET_LOADING = 'SET_LOADING';
const SET_PRODUCTS = 'SET_PRODUCTS';
const SET_ONE_PRODUCT = 'SET_ONE_PRODUCT';
const SHOW_PRODUCT_MODAL = 'SHOW_PRODUCT_MODAL';
const SHOW_WISHLIST_MODAL = 'SHOW_WISHLIST_MODAL';

export {
  SET_LOADING,
  SET_PRODUCTS,
  SET_ONE_PRODUCT,
  SHOW_PRODUCT_MODAL,
  SHOW_WISHLIST_MODAL
};
