const ADD_PRODUCT_TO_WISHLIST = 'ADD_PRODUCT_TO_WISHLIST';
const REMOVE_PRODUCT_FROM_WISHLIST = 'REMOVE_PRODUCT_FROM_WISHLIST';
const OPEN_WISHLIST = 'OPEN_WISHLIST';
const CLOSE_WISHLIST = 'CLOSE_WISHLIST';

export {
  ADD_PRODUCT_TO_WISHLIST,
  REMOVE_PRODUCT_FROM_WISHLIST,
  OPEN_WISHLIST,
  CLOSE_WISHLIST,
}
