const ADD_PRODUCT_TO_WISHLIST = 'ADD_PRODUCT_TO_WISHLIST';
const REMOVE_PRODUCT_FROM_WISHLIST = 'REMOVE_PRODUCT_FROM_WISHLIST';
const EMPTY_WISHLIST = 'EMPTY_WISHLIST';
const TRANSFER_DATA_TO_WISHLIST_FROM_DB = 'TRANSFER_DATA_TO_WISHLIST_FROM_DB';


export {
  ADD_PRODUCT_TO_WISHLIST,
  REMOVE_PRODUCT_FROM_WISHLIST,
  EMPTY_WISHLIST,
  TRANSFER_DATA_TO_WISHLIST_FROM_DB,
}
